<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TX717-7310MSL" name="Default test" tests="1" failures="1" timestamp="3 Oct 2017 18:02:57 GMT" time="3.9" errors="0">
  <testcase name="runTC_NewApplication_HomePageValidation" time="3.88" classname="testscripts.NewApplication.TC_NewApplication_HomePageValidation">
    <failure type="com.cognizant.framework.FrameworkException" message="Unhandled Execution Mode!">
      <![CDATA[com.cognizant.framework.FrameworkException: Unhandled Execution Mode!
	at com.cognizant.Craft.DriverScript.createTestLogHeader(DriverScript.java:479)
	at com.cognizant.Craft.DriverScript.initializeTestReport(DriverScript.java:377)
	at com.cognizant.Craft.DriverScript.driveTestExecution(DriverScript.java:148)
	at testscripts.NewApplication.TC_NewApplication_HomePageValidation.runTC_NewApplication_HomePageValidation(TC_NewApplication_HomePageValidation.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runTC_NewApplication_HomePageValidation -->
</testsuite> <!-- Default test -->
